version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: demo_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d # Runs init.sql on startup

  trino:
    image: trinodb/trino:latest
    container_name: trino-server
    ports:
      - "8080:8080"
    volumes:
      - ./etc/catalog:/etc/trino/catalog # Mounts the mysql connector config
    depends_on:
      - mysql